### ISSUE TITLE
[File a bug report for the Demon Implant]: Keeps sending checkin request

### ISSUE THREAD

**Issue by muhyuddin** [HavocFramework/Havoc#226] opened 2022-11-10 23:25 UTC
### What happened?

Sometimes while working fine, the implant doesn't respond to command requests e.g. download/upload and starts sending check-in requests, but the server doesn't handle it as the implant id is already registered. Check-in ping time is updated to 0 sec when a packet is received, but no command is executed.

Suggestion:
Re-registering the implant can be implemented whenever it receives a new check-in request with an already used id or any other mechanism, not just ignoring it. 

![image](https://user-images.githubusercontent.com/34711191/201227128-e55efe1b-3119-4d8f-9768-94726fd5a6ff.png)

![image](https://user-images.githubusercontent.com/34711191/201226785-c9ee7266-a2d8-4b2c-90cb-916f7deb3916.png)

### Did You Do a Pull First?

Latest (You performed a pull first)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by cjzh781119** [comment] 2022-12-05 09:30
the same question
sorry for issue #237 ,can you delete #237

**Comment by Cracked5pider** [comment] 2022-12-05 14:54
btw does this issue still persists? since I couldn't manage to reproduce the error.

**Comment by cjzh781119** [comment] 2022-12-06 00:42
> btw does this issue still persists? since I couldn't manage to reproduce the error.

yes,it is
![Screenshot from 2022-12-06 08-41-58](https://user-images.githubusercontent.com/30364306/205777808-d2ccbb5a-2b1c-4cdc-a162-05e04235c76c.png)
![Screenshot from 2022-12-06 08-42-29](https://user-images.githubusercontent.com/30364306/205777831-e6de1a54-2a11-4347-b613-57ef0c52a3ef.png)

**Comment by cjzh781119** [comment] 2022-12-06 09:04
i think the issue is in demon.c main loop
init---online---dispatch command----disconnect----reconnect---reinit(error is here)

i changed CommandDispatcher()'s main loop in command.c 
change "return" to "continue";
maintain agent which has been inited in the main loop , it works

**Comment by S4ntiagoP** [comment] 2023-02-24 21:53
I believe that this has already been fixed on https://github.com/HavocFramework/Havoc/pull/257

**Comment by S4ntiagoP** [comment] 2023-02-28 01:23
already fixed, thanks for reporting!

**Closed by S4ntiagoP** 2023-02-28 01:23 UTC
Labels: bug
