### ISSUE TITLE
Payload Compile Error

### ISSUE THREAD

**Issue by Andi-A** [HavocFramework/Havoc#133] opened 2022-10-05 10:06 UTC
After clicking generate at the payload console it hits me back with the following errors: 

Couldn't compile implant: exit status 1
Compile output: In file in
e/Demon.h:11
from Source/Core/Command.c:1

![Screenshot from 2022-10-05 13-19-10](https://user-images.githubusercontent.com/78365161/194048804-6bf90bb2-0517-4bd2-abb5-452eda86ba1e.png)

Platform: Ubuntu 22.04
Python version: Python 3.10.6

**Comment by Cracked5pider** [comment] 2022-10-05 12:13
Duplicate of #105.

**Closed by Cracked5pider** 2022-10-05 12:13 UTC
